### ISSUE TITLE
no need to support custom handler

### ISSUE THREAD

**Issue by defunctzombie** [baryshev/connect-domain#3]
Why not just always call next(err) instead of supporting the custom handler. That way the middleware becomes simpler since you just create a domain object and capture any errors from it. You let the normal connect stack handle error propagation.

**Comment by defunctzombie** [comment]
I did a quick edit to show what I was describing:
https://github.com/shtylman/connect-domain/blob/master/lib/connect-domain.js

**Comment by baryshev** [comment]
It's just old code support. Removed now.

About your edit:

``` js
res.on('close', reqDomain.dispose.bind(reqDomain));
```

works slower than

``` js
res.on('close', function () {
    reqDomain.dispose();
});
```

On my environmet benchmarks shows ~2650 rps with `function` vs ~2350 rps with `bind`.

**Comment by defunctzombie** [comment]
cool! Also, not sure why you have the whole thing in a closure, but that could go as well.

Yea, I figured the bind might be a bit slower.

**Comment by baryshev** [comment]
Closure is a jsLint recommendation to force StrictMode. But i'm unsure about is it realy needed here.

**Comment by defunctzombie** [comment]
I would say not needed :) It isn't really the idiosyncratic way to write modules in node.

**Comment by baryshev** [comment]
Ok :) Removed.
