### ISSUE TITLE
Could the Domain Error be typed?

### ISSUE THREAD

**Issue by fzaninotto** [baryshev/connect-domain#5]
When recovering from an `uncaughtException`, one may want to restart the server (left in an "unstable" state). The problem is that your middleware does not "mark" errors redirected to the connect error handler, so there is no way to tell the difference between an error voluntarily passed to `next(err)` and an `uncaughtException` legitimately caught by `connect-domain`.

One solution would be to decorate the error with a custom Error type, so that the connect error handler could restart when errors come from `connect-domain`.

**Comment by baryshev** [comment]
Restart not required when we using domains. This module works in my production without any problems with several months uptime.

**Comment by fzaninotto** [comment]
Nevermind, the Error objects caught by `domain` ARE easily identified, not because they subclass `Error`, but because they have additional properties like `domain` (see http://nodejs.org/api/domain.html). So what I want to achieve can be done without any modification to your middleware:

``` js
app.use(connectDomain());
// custom error handler
app.use(function(err, req, res, next) {
  console.error(err);
  res.status(500).render("500.html", function(renderingError, html) {
    if (typeof err.domain !== 'undefined') {
      // uncaughtException caught by domain: exit after rendering the error 500 page
      process.exit(1);
    }
  });
});
```
